lanauage: node_js
node_js:
  - 'node'
cache:
  directories: node_modules
install: npm install
script: 
  - npm run test:coverage
  - npm run codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)